<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>PulsePro Admin</title>
<script type='text/javascript' src='assets/js/jquery-1.4.2.min.js'></script>
<script type='text/javascript' src='assets/js/jquery.tipsy.js'></script>
<script type='text/javascript' src='assets/js/impromptu/jquery-impromptu.js'></script>
<script type='text/javascript' src='assets/js/functions.js'></script>
<link href='http://fonts.googleapis.com/css?family=Open+Sans|Oswald' rel='stylesheet' type='text/css'/>
<link rel='stylesheet' href='assets/css/tipsy.css'></link>
<link rel='stylesheet' href='assets/js/impromptu/default.css'></link>
<link rel='stylesheet' href='assets/css/pulse.admin.css'></link>
</head>
<body>
<div id="header">
	<h1>PulsePro Admin</h1>
	<div id="admin-actions">
		<a href="settings.php">Settings</a> &bull; <a href="logout.php">Logout</a>
	</div>
	<div class="clear"></div>
</div>
